### ISSUE TITLE
Analyze which part of jQuery does UJS depend on

### ISSUE THREAD

**Issue by liudangyi** [liudangyi/jquery-ujs#1]
And work out solutions to replace them.

**Comment by liudangyi** [comment]
I've found a great article called [you might not need jQuery](http://youmightnotneedjquery.com), which provides a comprehensive analysis of what jQuery provides and how to alternative it.

| jQuery Function | Alternative | IE Support |
| --- | --- | --- |
| $ selector / $(el).find with `:disabled` `:enabled` and `:not` | [querySelector](http://caniuse.com/#feat=queryselector) | IE9 (IE8 doesn't support CSS3 selectors) |
| $.Event / $(el).trigger | [CustomEvent](http://caniuse.com/#feat=customevent) | IE9 (with a non-standard API) |
| $.ajax | XMLHttpRequest | IE7 |
| $(el).data / $(el).removeData | Store data on DOM ([like jQuery](https://github.com/jquery/jquery/blob/58c6ca9822afa42d3b40cca8edb0abe90a2bcb34/src/data/Data.js#L34)) | Unknown |
| $(el).is | [matches() DOM method](http://caniuse.com/#feat=matchesselector) | IE9 (with a non-standard API) |
| $(el).serialize | Copy from [jQuery](https://github.com/jquery/jquery/blob/58c6ca9822afa42d3b40cca8edb0abe90a2bcb34/src/serialize.js#L93) | Unknown |
| $(el).attr | Element.getAttribute | IE6 |
| $(els).map / $(els).filter / $(els).each | Array.prototype.forEach, Array.prototype.map, Array.prototype.filter | IE9, or use polyfills on IE8 |
| $(el).html | el.innerHTML | IE6 |
| $(el).bind / $(el).bind | el.addEventListener / el.removeEventListener | IE8 (with a non-standard API) |
| $(el).delegate | el.addEventListener + event.target.matches | IE9 |

**Comment by liudangyi** [comment]
Some additional features

| Feature | IE Support |
| --- | --- |
| Asynchronous file upload (FormData) | [IE10 with bugs](http://caniuse.com/#feat=xhr2) |

**Comment by liudangyi** [comment]
Conclusion: we should target IE9 and mark IE8 as not supported.

**Comment by pixeltrix** [comment]
DHH is on record that a native UJS is for new projects going forward so only need to match Basecamp's browser requirements: https://basecamp.com/help/3/guides/account/browsers

> Internet Explorer 11+
> Google Chrome: latest version
> Mozilla Firefox: latest version
> Apple Safari: 7+

**Comment by liudangyi** [comment]
In this sense it would be much easier and we can ignore IE9 since it has a lot of quirks in API.

**Comment by liudangyi** [comment]
I've finished all the tasks mentioned in this issue. So close it.
