### ISSUE TITLE
Better organization of the source code

### ISSUE THREAD

**Issue by liudangyi** [liudangyi/jquery-ujs#2]
In fact there are two problems.
1. How to manage the dependency between different modules after splitting the code.
2. How to package these code (with or without compression) and distribute it in a single file.

We have several options. If we prefer JavaScript stuff, we can use [browserify](http://browserify.org) or [webpack](https://webpack.github.io/docs/library-and-externals.html). Or we can simply use [sprockets](https://github.com/rails/sprockets). The pro of the first choice is that these tools are more powerful and can really understand dependency, with the cost of additional code at runtime.

**Comment by pixeltrix** [comment]
> 1. How to manage the dependency between different modules after splitting the code.

I don't think there's any point in distributing separate modules so whatever's the best/most convenient tool for compiling to a single file. I definitely think we should be writing it in ES6 though.

> 1. How to package these code (with or without compression) and distribute it in a single file.

We should be as flexible as possible without imposing too much of a maintenance burden. So at a minimum we should publish an npm module and source gem like we do for Turbolinks 5 - bower is debatable but if it's easy to automate that as part of the publishing process then we should probably do it.

**Comment by liudangyi** [comment]
> I definitely think we should be writing it in ES6 though.

Does that mean that we should compile code using Babel? Some polyfills may add unnecessary code to generated file. 

Browserify or Webpack will also add extra code. I'll do an experiment to check how much overload they will add.

**Comment by liudangyi** [comment]
Webpack will add an extra 218 bytes while browserify will add 498 bytes. So choose webpack. :smile:
