### ISSUE TITLE
Code style: removing semicolons

### ISSUE THREAD

**Issue by liudangyi** [liudangyi/jquery-ujs#3]
It's es6 now and many developers have removed semicolons from their projects. While semicolons are unnecessary in most situations, it adds inconvenience to developers. 

@pixeltrix I would like to remove semicolons from UJS and what do you think?

**Comment by liudangyi** [comment]
And I decide to move from jshint to eslint because the later is more actively developed and supports es6 better.

**Comment by pixeltrix** [comment]
👍
